/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.InterfazGrafica;

import javax.swing.JOptionPane;
import proyecto.ABB_Productos.Estructura.ABB;
import static proyecto.Proyecto.ARCHIVO1;
import static proyecto.Proyecto.arbol;
import static proyecto.Proyecto.inventario;

import proyecto.inventario.InventarioManager;
import proyecto.persistencia.productoPersistencia;
import proyecto.pojo.Producto;

/**
 *Interfaz para agregar productos
 * @author juego
 */
public class AgregarView extends javax.swing.JFrame {

    
    
    
    /**
     * Constructor sin parametros para la interfaz agregar
     */
    public AgregarView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panel_titulo = new javax.swing.JPanel();
        btn_salir = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_precio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_clave = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_cantidad = new javax.swing.JTextField();
        btn_agregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_titulo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btn_salir.setBackground(new java.awt.Color(0, 122, 255));
        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/resources/img_iconos/cerrar-sesion (1).png"))); // NOI18N
        btn_salir.setPreferredSize(new java.awt.Dimension(32, 35));
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        panel_titulo.add(btn_salir);

        jLabel7.setPreferredSize(new java.awt.Dimension(620, 25));
        panel_titulo.add(jLabel7);

        jLabel3.setBackground(new java.awt.Color(243, 243, 243));
        jLabel3.setFont(new java.awt.Font("HP Simplified Hans", 1, 36)); // NOI18N
        jLabel3.setText("Agregar Productos");
        panel_titulo.add(jLabel3);
        panel_titulo.add(jLabel1);

        getContentPane().add(panel_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 60));

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel2.setBackground(new java.awt.Color(243, 243, 243));
        jLabel2.setFont(new java.awt.Font("HP Simplified Jpan", 1, 18)); // NOI18N
        jLabel2.setText("Precio:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        txt_precio.setForeground(new java.awt.Color(207, 207, 207));
        txt_precio.setToolTipText("Texto");
        txt_precio.setName(""); // NOI18N
        txt_precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_precioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 275;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        jPanel1.add(txt_precio, gridBagConstraints);
        txt_precio.getAccessibleContext().setAccessibleDescription("fffff");

        jLabel4.setBackground(new java.awt.Color(243, 243, 243));
        jLabel4.setFont(new java.awt.Font("HP Simplified Jpan", 1, 18)); // NOI18N
        jLabel4.setText("Clave:");
        jLabel4.setMaximumSize(new java.awt.Dimension(200, 19));
        jLabel4.setMinimumSize(new java.awt.Dimension(200, 19));
        jLabel4.setPreferredSize(new java.awt.Dimension(200, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 20, 0, 0);
        jPanel1.add(jLabel4, gridBagConstraints);

        txt_clave.setForeground(new java.awt.Color(207, 207, 207));
        txt_clave.setToolTipText("Texto");
        txt_clave.setName(""); // NOI18N
        txt_clave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_claveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 275;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        jPanel1.add(txt_clave, gridBagConstraints);

        jLabel5.setBackground(new java.awt.Color(243, 243, 243));
        jLabel5.setFont(new java.awt.Font("HP Simplified Jpan", 1, 18)); // NOI18N
        jLabel5.setText("Nombre:");
        jLabel5.setMaximumSize(new java.awt.Dimension(200, 19));
        jLabel5.setMinimumSize(new java.awt.Dimension(200, 19));
        jLabel5.setPreferredSize(new java.awt.Dimension(200, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 0, 0);
        jPanel1.add(jLabel5, gridBagConstraints);

        txt_nombre.setForeground(new java.awt.Color(207, 207, 207));
        txt_nombre.setToolTipText("Texto");
        txt_nombre.setName(""); // NOI18N
        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 275;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        jPanel1.add(txt_nombre, gridBagConstraints);

        jLabel6.setBackground(new java.awt.Color(243, 243, 243));
        jLabel6.setFont(new java.awt.Font("HP Simplified Jpan", 1, 18)); // NOI18N
        jLabel6.setText("Cantidad:");
        jLabel6.setMaximumSize(new java.awt.Dimension(200, 19));
        jLabel6.setMinimumSize(new java.awt.Dimension(200, 19));
        jLabel6.setPreferredSize(new java.awt.Dimension(200, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 20, 0, 0);
        jPanel1.add(jLabel6, gridBagConstraints);

        txt_cantidad.setForeground(new java.awt.Color(207, 207, 207));
        txt_cantidad.setToolTipText("Texto");
        txt_cantidad.setName(""); // NOI18N
        txt_cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cantidadActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 275;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        jPanel1.add(txt_cantidad, gridBagConstraints);

        btn_agregar.setFont(new java.awt.Font("HP Simplified Hans", 1, 18)); // NOI18N
        btn_agregar.setText("Agregar");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 222;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 70, 80, 320);
        jPanel1.add(btn_agregar, gridBagConstraints);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1000, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_precioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_precioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_precioActionPerformed

    private void txt_claveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_claveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_claveActionPerformed

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void txt_cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cantidadActionPerformed
        
    }//GEN-LAST:event_txt_cantidadActionPerformed
    /**
     * Action para que agregue el producto
     * @param evt 
     */
    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        try{
            String clave = txt_clave.getText();
            String nombre = txt_nombre.getText();
            // cast
            String cant = txt_cantidad.getText();
            String prec = txt_precio.getText();
            
            
            if(txt_clave.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Faltan datos");
                return;
            }
            
            if(txt_nombre.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Faltan datos");
                return;
            }
            
            if(txt_cantidad.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Faltan datos");
                return;
            }
            
            if(txt_precio.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Faltan datos");
                return;
            }
            
            int cantidad = Integer.parseInt(cant);
            double precio = Double.parseDouble(prec);
            
            
            Producto p = new Producto(clave, nombre, cantidad, precio);
            inventario.agregarProducto(p);
            

            JOptionPane.showMessageDialog(this, "Producto registrado correctamente");
            txt_clave.setText("");
            txt_nombre.setText("");
            txt_cantidad.setText("");
            txt_precio.setText("");
            
        }catch(Exception ParseException){
            JOptionPane.showMessageDialog(this, "Algo sucedio mal, intentalo de nuevo");
        }
        
        try{
            productoPersistencia.guardarComoJson(ARCHIVO1, 
                                                arbol.ordenarDatos(true));
            
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
        
        
        
        
        
        
    }//GEN-LAST:event_btn_agregarActionPerformed
    /**
     * Action para cuando se presione el boton de salir
     * @param evt 
     */
    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        this.dispose();
        new PrincipalView().setVisible(true);
           
    }//GEN-LAST:event_btn_salirActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panel_titulo;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_clave;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_precio;
    // End of variables declaration//GEN-END:variables
}
