/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package proyecto.InterfazGrafica;

import javax.swing.JOptionPane;
import static proyecto.Proyecto.ARCHIVO1;
import static proyecto.Proyecto.arbol;
import static proyecto.Proyecto.inventario;
import proyecto.persistencia.productoPersistencia;
import proyecto.pojo.Producto;

/**
 *Dialog para poner los datos especificos del producto que se va a editar
 * @author juego
 */
public class EditarDialog extends javax.swing.JDialog {
    private Producto producto;
    
    /**
     * Creates new form EditarDialog
     */
    public EditarDialog(java.awt.Frame parent, boolean modal, Producto producto) {
        super(parent, modal);
        initComponents();
        
        this.producto = producto;
        cargarDatosProducto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btn_guardar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_clave = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_cantidad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_precio = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(598, 60));

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_guardar);

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cancelar);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jLabel4.setBackground(new java.awt.Color(243, 243, 243));
        jLabel4.setFont(new java.awt.Font("HP Simplified Jpan", 1, 18)); // NOI18N
        jLabel4.setText("Clave:");
        jLabel4.setMaximumSize(new java.awt.Dimension(200, 19));
        jLabel4.setMinimumSize(new java.awt.Dimension(200, 19));
        jLabel4.setPreferredSize(new java.awt.Dimension(200, 19));

        jLabel5.setBackground(new java.awt.Color(243, 243, 243));
        jLabel5.setFont(new java.awt.Font("HP Simplified Jpan", 1, 18)); // NOI18N
        jLabel5.setText("Nombre:");
        jLabel5.setMaximumSize(new java.awt.Dimension(200, 19));
        jLabel5.setMinimumSize(new java.awt.Dimension(200, 19));
        jLabel5.setPreferredSize(new java.awt.Dimension(200, 19));

        txt_clave.setForeground(new java.awt.Color(207, 207, 207));
        txt_clave.setToolTipText("Texto");
        txt_clave.setName(""); // NOI18N
        txt_clave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_claveActionPerformed(evt);
            }
        });

        txt_nombre.setForeground(new java.awt.Color(207, 207, 207));
        txt_nombre.setToolTipText("Texto");
        txt_nombre.setName(""); // NOI18N
        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(243, 243, 243));
        jLabel6.setFont(new java.awt.Font("HP Simplified Jpan", 1, 18)); // NOI18N
        jLabel6.setText("Cantidad:");
        jLabel6.setMaximumSize(new java.awt.Dimension(200, 19));
        jLabel6.setMinimumSize(new java.awt.Dimension(200, 19));
        jLabel6.setPreferredSize(new java.awt.Dimension(200, 19));

        txt_cantidad.setForeground(new java.awt.Color(207, 207, 207));
        txt_cantidad.setToolTipText("Texto");
        txt_cantidad.setName(""); // NOI18N
        txt_cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cantidadActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(243, 243, 243));
        jLabel2.setFont(new java.awt.Font("HP Simplified Jpan", 1, 18)); // NOI18N
        jLabel2.setText("Precio:");

        txt_precio.setForeground(new java.awt.Color(207, 207, 207));
        txt_precio.setToolTipText("Texto");
        txt_precio.setName(""); // NOI18N
        txt_precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_precioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_clave, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(283, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_clave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(187, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_claveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_claveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_claveActionPerformed

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void txt_cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cantidadActionPerformed

    }//GEN-LAST:event_txt_cantidadActionPerformed

    private void txt_precioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_precioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_precioActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        try {
            String nuevoNombre = txt_nombre.getText();
        
        
            int nuevaCantidad = Integer.parseInt(txt_cantidad.getText());
            double nuevoPrecio = Double.parseDouble(txt_precio.getText());

       
        if (nuevoNombre.trim().isEmpty() || nuevaCantidad < 0 || nuevoPrecio < 0) {
            JOptionPane.showMessageDialog(this, 
                "El nombre no puede estar vacío y los valores deben ser positivos.", 
                "Error de Validación", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        // Le pasamos el objeto a editar (producto) y los nuevos valores.
        boolean exito = inventario.editarProducto(
            this.producto, 
            nuevoNombre, 
            nuevaCantidad, 
            nuevoPrecio
        );
        
        
        if (exito) {
            JOptionPane.showMessageDialog(this, "Producto editado con éxito en el inventario.");
            this.dispose(); 
        } else {
            // Este caso (retorno 'false') solo ocurriría si el Manager no encontrara el producto,
            // pero como ya lo tenemos, es poco probable.
            JOptionPane.showMessageDialog(this, "Error al intentar guardar los cambios.", "Error", JOptionPane.ERROR_MESSAGE);
        }

        } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, 
            "La cantidad y el precio deben ser números válidos.", 
            "Error de Formato", JOptionPane.ERROR_MESSAGE);
        }
        try{
            productoPersistencia.guardarComoJson(ARCHIVO1, 
                                                arbol.ordenarDatos(true));
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
            
        
    }//GEN-LAST:event_btn_guardarActionPerformed
    /**
     * Metodo para cancelar y salir
     * @param evt 
     */
    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        int confirmacion = JOptionPane.showConfirmDialog(
            this, 
            "¿Está seguro que desea salir sin guardar los cambios?", 
            "Confirmar Cancelación", 
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if (confirmacion == JOptionPane.YES_OPTION) {
            
            this.dispose();
        }
    }//GEN-LAST:event_btn_cancelarActionPerformed
    /**
     * Metodo para cargar los datos en el Dialog
     */
    private void cargarDatosProducto() {
        
        txt_clave.setText(producto.getClave()); 
        txt_clave.setEnabled(false); 
        
        // Nombre
        txt_nombre.setText(producto.getNombre());
        
        // Cantidad (Convertir el int a String)
        txt_cantidad.setText(String.valueOf(producto.getCantidad()));
        
        // Precio (Convertir el double a String)
        txt_precio.setText(String.valueOf(producto.getPrecio()));
    }  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_clave;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_precio;
    // End of variables declaration//GEN-END:variables
}
