/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.InterfazGrafica;

import java.io.FileNotFoundException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static proyecto.Proyecto.ARCHIVO1;
import static proyecto.Proyecto.arbol;
import static proyecto.Proyecto.inventario;
import proyecto.inventario.InventarioManager;
import proyecto.persistencia.productoPersistencia;
import proyecto.pojo.Producto;

/**
 *Clase para mostrar los productos con recorrido Inorde o metodos de ordenamiento (MergeSort y QuickSort).
 * @author juego
 */
public class EditarView extends javax.swing.JFrame {
    private List<Producto> productos;

    /**
     * 
     * @throws FileNotFoundException 
     */
    public EditarView() throws FileNotFoundException {
        initComponents();
        productoPersistencia.cargarJson(ARCHIVO1);
        mostrarTablaInorden();
        productos = productoPersistencia.cargarJson(ARCHIVO1);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_salir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_editar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_productos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/resources/img_iconos/cerrar-sesion (1).png"))); // NOI18N
        btn_salir.setPreferredSize(new java.awt.Dimension(60, 25));
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        jPanel1.add(btn_salir);

        jLabel5.setPreferredSize(new java.awt.Dimension(50, 25));
        jPanel1.add(jLabel5);

        jLabel1.setFont(new java.awt.Font("HP Simplified Hans", 1, 24)); // NOI18N
        jLabel1.setText("Tabla de productos ");
        jPanel1.add(jLabel1);

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setMaximumSize(new java.awt.Dimension(100, 25));
        jLabel4.setPreferredSize(new java.awt.Dimension(500, 25));
        jPanel1.add(jLabel4);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel3.setPreferredSize(new java.awt.Dimension(880, 70));

        btn_editar.setBackground(new java.awt.Color(0, 122, 255));
        btn_editar.setFont(new java.awt.Font("HP Simplified Hans", 1, 18)); // NOI18N
        btn_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/resources/img_iconos/editar.png"))); // NOI18N
        btn_editar.setText("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });
        jPanel3.add(btn_editar);

        btn_eliminar.setBackground(new java.awt.Color(0, 122, 255));
        btn_eliminar.setFont(new java.awt.Font("HP Simplified Hans", 1, 18)); // NOI18N
        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/resources/img_iconos/eliminar.png"))); // NOI18N
        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        jPanel3.add(btn_eliminar);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        tbl_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Clave", "Nombre", "Cantidad", "Precio"
            }
        ));
        jScrollPane1.setViewportView(tbl_productos);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

   /**
     * Action para el boton de salir
     * @param evt 
     */
    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        this.dispose();
        new PrincipalView().setVisible(true);
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        int indexselected = this.tbl_productos.getSelectedRow();
        if(indexselected < 0){
            JOptionPane.showMessageDialog(this,
                         "Debes seleccionar el registro que vas a editar",
                         "Advertencia", 
                         JOptionPane.WARNING_MESSAGE);
            return;
        }
        //obtenemos el producto que seleccionamos
        // guardamos la clave y se lo pasamos como parametro al metodo buscar, que nos devolvera un producto
        //el cual usaremos para modificar en el dialog
        DefaultTableModel model = (DefaultTableModel) this.tbl_productos.getModel();
        String claveProducto = model.getValueAt(indexselected, 0).toString();
        Producto productoEditar = inventario.buscarProducto(claveProducto);
        
        if(productoEditar != null){
            new EditarDialog(this, true, productoEditar).setVisible(true);
            mostrarTablaInorden();
        } else {
            JOptionPane.showMessageDialog(this, "Error: no se pudo encontrar el producto");
        }
        
        try{
            productoPersistencia.guardarComoJson(ARCHIVO1, 
                                                arbol.ordenarDatos(true));
            
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
        
        
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        int filaSeleccionada = this.tbl_productos.getSelectedRow();
    
        if (filaSeleccionada < 0) {
            JOptionPane.showMessageDialog(this,
                "Debes seleccionar el producto que deseas eliminar.",
                "Advertencia", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
    
    
        DefaultTableModel model = (DefaultTableModel) this.tbl_productos.getModel();
    
    
        String claveProducto = model.getValueAt(filaSeleccionada, 0).toString(); 
    
    
        int confirmacion = JOptionPane.showConfirmDialog(
            this, 
            "¿Estás seguro de que deseas eliminar el producto con clave: " + claveProducto + "?", 
            "Confirmar Eliminación", 
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );
    
        if (confirmacion == JOptionPane.YES_OPTION) {
        
        //Llamar al méTODO para eliminar el producto
       
            inventario.eliminarProducto(claveProducto); 
        
        
            JOptionPane.showMessageDialog(this, 
                    "Producto con clave " + claveProducto + " eliminado con éxito.", 
                    "Eliminación Exitosa", 
                    JOptionPane.INFORMATION_MESSAGE);
            mostrarTablaInorden();
            
        }
        
        try{
            productoPersistencia.guardarComoJson(ARCHIVO1, 
                                                arbol.ordenarDatos(true));
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btn_eliminarActionPerformed
        /**
     * metodo para mostrar la tabla, llamandolo desde inventario
     */
    public void mostrarTablaInorden(){
        DefaultTableModel modelo = inventario.getProductoInorden();
        tbl_productos.setModel(modelo);
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_productos;
    // End of variables declaration//GEN-END:variables
}
