/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package proyecto.InterfazGrafica;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import static proyecto.Proyecto.ARCHIVO2;
import static proyecto.Proyecto.inventario;
import proyecto.persistencia.eliminadosPersistencia;
import proyecto.persistencia.productoPersistencia;
import proyecto.pojo.Eliminado;
import proyecto.pojo.Eliminado;
import proyecto.pojo.Producto;

/**
 *
 * @author juego
 */
public class EliminarDialog extends javax.swing.JDialog {
    private Producto producto;
    /**
     * Creates new form EliminarDialog
     */
    public EliminarDialog(java.awt.Frame parent, boolean modal, Producto producto) {
        super(parent, modal);
        initComponents();
        this.producto = producto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn_eliminar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_fecha = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_clave = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_razon = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btn_eliminar.setFont(new java.awt.Font("HP Simplified Hans", 1, 14)); // NOI18N
        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_eliminar);

        btn_cancelar.setFont(new java.awt.Font("HP Simplified Hans", 1, 14)); // NOI18N
        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_cancelar);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(243, 243, 243));
        jLabel4.setFont(new java.awt.Font("HP Simplified Jpan", 1, 18)); // NOI18N
        jLabel4.setText("Fecha:");
        jLabel4.setMaximumSize(new java.awt.Dimension(200, 19));
        jLabel4.setMinimumSize(new java.awt.Dimension(200, 19));
        jLabel4.setPreferredSize(new java.awt.Dimension(200, 19));
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 60, 30));

        txt_fecha.setForeground(new java.awt.Color(207, 207, 207));
        txt_fecha.setToolTipText("Texto");
        txt_fecha.setName(""); // NOI18N
        txt_fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fechaActionPerformed(evt);
            }
        });
        jPanel3.add(txt_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 290, 30));

        jLabel5.setBackground(new java.awt.Color(243, 243, 243));
        jLabel5.setFont(new java.awt.Font("HP Simplified Jpan", 1, 18)); // NOI18N
        jLabel5.setText("Clave:");
        jLabel5.setMaximumSize(new java.awt.Dimension(200, 19));
        jLabel5.setMinimumSize(new java.awt.Dimension(200, 19));
        jLabel5.setPreferredSize(new java.awt.Dimension(200, 19));
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 41, 60, 30));

        txt_clave.setForeground(new java.awt.Color(207, 207, 207));
        txt_clave.setToolTipText("Texto");
        txt_clave.setName(""); // NOI18N
        txt_clave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_claveActionPerformed(evt);
            }
        });
        jPanel3.add(txt_clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 290, 30));

        jLabel6.setBackground(new java.awt.Color(243, 243, 243));
        jLabel6.setFont(new java.awt.Font("HP Simplified Jpan", 1, 18)); // NOI18N
        jLabel6.setText("Razon:");
        jLabel6.setMaximumSize(new java.awt.Dimension(200, 19));
        jLabel6.setMinimumSize(new java.awt.Dimension(200, 19));
        jLabel6.setPreferredSize(new java.awt.Dimension(200, 19));
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 60, 30));

        txt_razon.setForeground(new java.awt.Color(207, 207, 207));
        txt_razon.setToolTipText("Texto");
        txt_razon.setName(""); // NOI18N
        txt_razon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_razonActionPerformed(evt);
            }
        });
        jPanel3.add(txt_razon, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 890, 30));

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fechaActionPerformed
    /**
     * Metodo para guardar el elemento eliminado
     * @param evt 
     */
    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        String clave = this.txt_clave.getText().trim(); 
        String razon = this.txt_razon.getText().trim();
        String fechaString = this.txt_fecha.getText().trim();
    
        Date fechaParseada = null;
    
        if (clave.isEmpty() || razon.isEmpty() || fechaString.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Debe introducir la Clave, la Razón y la Fecha.",
                "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
            formatter.setLenient(false);
            fechaParseada = formatter.parse(fechaString);

        } catch (java.text.ParseException e) {
            JOptionPane.showMessageDialog(this,
                "El formato de la fecha es inválido. Use el formato dd/MM/yyyy.",
                "Error de Formato", JOptionPane.ERROR_MESSAGE);
            return;
        }
    
        int confirmacion = JOptionPane.showConfirmDialog(
            this,
            "¿Confirma la eliminación del producto con clave: " + clave + "?",
            "Confirmar Eliminación", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE
        );
    
        if (confirmacion == JOptionPane.YES_OPTION) {
        
            try {
                Eliminado registro = new Eliminado(clave, razon, fechaParseada);
            
                inventario.historialEliminaciones.add(registro); 
            
                inventario.eliminarProducto(clave); 
                
            
               eliminadosPersistencia.guardarComoJson(ARCHIVO2, inventario.historialEliminaciones);
            
                JOptionPane.showMessageDialog(this,
                    "Producto eliminado, registrado y guardado en JSON.",
                    "Operación Exitosa", JOptionPane.INFORMATION_MESSAGE);
            
                this.dispose(); 
            
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                    "Error durante la operación (ABB/JSON): " + e.getMessage(),
                    "Error Interno", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void txt_claveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_claveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_claveActionPerformed

    private void txt_razonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_razonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_razonActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txt_clave;
    private javax.swing.JTextField txt_fecha;
    private javax.swing.JTextField txt_razon;
    // End of variables declaration//GEN-END:variables
}
