package proyecto.InterfazGrafica;


import java.util.Collections;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import proyecto.InterfazGrafica.PrincipalView;
import proyecto.historial.HistorialManager;
import proyecto.historial.Operacion;


/**
 *Interfaz para ver los Logs del usuario
 * @author juego
 */
public class LogView extends javax.swing.JFrame {

    /**
     * Constructor de la interfaz sin parametros
     */
    public LogView() {
        initComponents();
        mostrarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_salir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_logs = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/resources/img_iconos/cerrar-sesion (1).png"))); // NOI18N
        btn_salir.setPreferredSize(new java.awt.Dimension(45, 35));
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        jPanel1.add(btn_salir);

        jLabel2.setPreferredSize(new java.awt.Dimension(400, 35));
        jPanel1.add(jLabel2);

        jLabel1.setFont(new java.awt.Font("HP Simplified Hans", 1, 36)); // NOI18N
        jLabel1.setText("Historial de Operaciones");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 898, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        tbl_logs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Fecha/Hora", "Descripcion"
            }
        ));
        jScrollPane1.setViewportView(tbl_logs);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 898, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Action para ir a la ventana principal
     * @param evt 
     */
    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        this.dispose();
        new PrincipalView().setVisible(true);
    }//GEN-LAST:event_btn_salirActionPerformed
    /**
     * Metodo que devuelve un TableModel con los datos de logs
     * @return 
     */
    public DefaultTableModel getHistorialTableModel(){
        // Obtener la lista de operaciones (la pila como lista)
        List<Operacion> operaciones = HistorialManager.getInstance().obtenerHistorial();
        
        
        
        // Definir columnas
        String[] columnas = {"Fecha/Hora", "Descripción"};
        DefaultTableModel model = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;  // La tabla NO se puede editar
            }
        };
        
        // Llenar filas con las operaciones
        for (Operacion op : operaciones) {
            Object[] fila = {
                op.getTimestamp().toString(),  // Formato: 2023-10-05T14:30:00
                op.getDescripcion()
            };
            model.addRow(fila);
        }
        
        return model;
    }
    /**
     * Metodo para actualizar la tabla ya con los datos
     */
    public void mostrarTabla(){
        DefaultTableModel model = getHistorialTableModel();
         String [] columnas = {"Fecha/Hora", "Descripcion"};
         
 
        
        
        
        tbl_logs.setModel(model);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_logs;
    // End of variables declaration//GEN-END:variables
}
