/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.InterfazGrafica;

import java.io.FileNotFoundException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static proyecto.Proyecto.ARCHIVO1;
import static proyecto.Proyecto.arbol;
import static proyecto.Proyecto.inventario;
import proyecto.inventario.InventarioManager;
import proyecto.persistencia.productoPersistencia;

/**
 *Interfaz para mostrar los productos con recorrido Inorde o metodos de ordenamiento (MergeSort y QuickSort).
 * @author juego
 */
public class MostrarView extends javax.swing.JFrame {
    

    /**
     * 
     * @throws FileNotFoundException 
     */
    public MostrarView() throws FileNotFoundException {
        initComponents();
        productoPersistencia.cargarJson(ARCHIVO1);
        mostrarTablaInorden();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_salir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btn_inorden = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_mergeSort = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btn_quickSort = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_productos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/resources/img_iconos/cerrar-sesion (1).png"))); // NOI18N
        btn_salir.setPreferredSize(new java.awt.Dimension(60, 25));
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        jPanel1.add(btn_salir);

        jLabel5.setPreferredSize(new java.awt.Dimension(50, 25));
        jPanel1.add(jLabel5);

        jLabel1.setFont(new java.awt.Font("HP Simplified Hans", 1, 24)); // NOI18N
        jLabel1.setText("Tabla de productos ");
        jPanel1.add(jLabel1);

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setMaximumSize(new java.awt.Dimension(100, 25));
        jLabel4.setPreferredSize(new java.awt.Dimension(100, 25));
        jPanel1.add(jLabel4);

        jToolBar1.setRollover(true);
        jToolBar1.setPreferredSize(new java.awt.Dimension(400, 50));

        btn_inorden.setBackground(new java.awt.Color(0, 122, 255));
        btn_inorden.setFont(new java.awt.Font("HP Simplified Hans", 1, 12)); // NOI18N
        btn_inorden.setText("Inorden");
        btn_inorden.setFocusable(false);
        btn_inorden.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_inorden.setMaximumSize(new java.awt.Dimension(100, 24));
        btn_inorden.setPreferredSize(new java.awt.Dimension(100, 40));
        btn_inorden.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_inorden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inordenActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_inorden);

        jLabel2.setMaximumSize(new java.awt.Dimension(50, 25));
        jLabel2.setPreferredSize(new java.awt.Dimension(40, 30));
        jToolBar1.add(jLabel2);

        btn_mergeSort.setBackground(new java.awt.Color(0, 122, 255));
        btn_mergeSort.setFont(new java.awt.Font("HP Simplified Hans", 1, 12)); // NOI18N
        btn_mergeSort.setText("MergeSort");
        btn_mergeSort.setFocusable(false);
        btn_mergeSort.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_mergeSort.setMaximumSize(new java.awt.Dimension(100, 24));
        btn_mergeSort.setPreferredSize(new java.awt.Dimension(100, 24));
        btn_mergeSort.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_mergeSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mergeSortActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_mergeSort);

        jLabel3.setMaximumSize(new java.awt.Dimension(50, 25));
        jLabel3.setPreferredSize(new java.awt.Dimension(40, 30));
        jToolBar1.add(jLabel3);

        btn_quickSort.setBackground(new java.awt.Color(0, 122, 255));
        btn_quickSort.setFont(new java.awt.Font("HP Simplified Hans", 1, 12)); // NOI18N
        btn_quickSort.setText("QuickSort");
        btn_quickSort.setFocusable(false);
        btn_quickSort.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_quickSort.setMaximumSize(new java.awt.Dimension(100, 24));
        btn_quickSort.setPreferredSize(new java.awt.Dimension(100, 24));
        btn_quickSort.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_quickSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quickSortActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_quickSort);

        jPanel1.add(jToolBar1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        tbl_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Clave", "Nombre", "Cantidad", "Precio"
            }
        ));
        jScrollPane1.setViewportView(tbl_productos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Metodo para que cargue la tabla en inorden, pulsando el boton.
     * @param evt 
     */
    private void btn_inordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inordenActionPerformed
        try{
            mostrarTablaInorden();
            JOptionPane.showMessageDialog(this, "Ordenado en Inorden");
        
        }catch (Exception ex){
            JOptionPane.showMessageDialog(this, "Error, intentalo de nuevo");
           
        }
        
         
    }//GEN-LAST:event_btn_inordenActionPerformed
    /**
     * Action para el boton de quick
     * @param evt 
     */
    private void btn_quickSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quickSortActionPerformed
       try{
            mostrarQuickSort();
            JOptionPane.showMessageDialog(this, "Ordenado con QuickSort");
        
        }catch (Exception ex){
            JOptionPane.showMessageDialog(this, "Error, intentalo de nuevo");
           
        }
    }//GEN-LAST:event_btn_quickSortActionPerformed
    /**
     * Action para el boton de salir
     * @param evt 
     */
    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        this.dispose();
        new PrincipalView().setVisible(true);
    }//GEN-LAST:event_btn_salirActionPerformed
    /**
     * Action para el boton de merge
     * @param evt 
     */
    private void btn_mergeSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mergeSortActionPerformed
        try{
            mostrarMergeSort();
            JOptionPane.showMessageDialog(this, "Ordenado con MergeSort");
        
        }catch (Exception ex){
            JOptionPane.showMessageDialog(this, "Error, intentalo de nuevo");
           
        }
    }//GEN-LAST:event_btn_mergeSortActionPerformed
    /**
     * metodo para mostrar la tabla, llamandolo desde inventario
     */
    public void mostrarTablaInorden(){
        DefaultTableModel modelo = inventario.getProductoInorden();
        tbl_productos.setModel(modelo);
    }
    /**
     * metodo para mostrar la tabla con ordenamiento QuickSort, llamandolo desde inventario
     */
    public void mostrarQuickSort(){
        DefaultTableModel modelo = inventario.getProductosQuickSort();
        tbl_productos.setModel(modelo);
    }
    /**
     * metodo para mostrar la tabla con ordenamiento MergeSort, llamandolo desde inventario
     */
    public void mostrarMergeSort(){
        DefaultTableModel modelo = inventario.getProductosMergeSort();
        tbl_productos.setModel(modelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_inorden;
    private javax.swing.JButton btn_mergeSort;
    private javax.swing.JButton btn_quickSort;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tbl_productos;
    // End of variables declaration//GEN-END:variables
}
