/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.InterfazGrafica;

import java.awt.Color;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *Clase para la interfaz principal
 * @author aleja
 */
public class PrincipalView extends javax.swing.JFrame {
    
    
   
    /**
     * Creates new form ProductosGUI
     */
    Color mouseEnterColor = new Color(25,118,120);
    Color mouseExitColor = new Color(37,37,38);
    public PrincipalView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_titulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sidebar_panel = new javax.swing.JPanel();
        btn_agregar = new javax.swing.JPanel();
        jlabel_agregarP1 = new javax.swing.JLabel();
        btn_mostrar = new javax.swing.JPanel();
        jlabel_mostrar = new javax.swing.JLabel();
        btn_editar = new javax.swing.JPanel();
        jlabel_editar = new javax.swing.JLabel();
        panel_barraAccion = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_Buscar = new javax.swing.JPanel();
        btn_Buscar1 = new javax.swing.JPanel();
        jlabel_buscar1 = new javax.swing.JLabel();
        btn_eliminar = new javax.swing.JPanel();
        jlabel_eliminar = new javax.swing.JLabel();
        texto_bienvenida = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_titulo.setBackground(new java.awt.Color(33, 150, 243));
        panel_titulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panel_titulo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 50));

        jLabel2.setBackground(new java.awt.Color(243, 243, 243));
        jLabel2.setFont(new java.awt.Font("HP Simplified Hans", 1, 24)); // NOI18N
        jLabel2.setText("Tienda de Productos");
        panel_titulo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 220, 30));

        getContentPane().add(panel_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 78));

        sidebar_panel.setBackground(new java.awt.Color(37, 37, 38));
        sidebar_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_agregar.setBackground(new java.awt.Color(37, 37, 38));
        btn_agregar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_agregarMouseEntered(evt);
            }
        });
        btn_agregar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlabel_agregarP1.setBackground(new java.awt.Color(51, 0, 255));
        jlabel_agregarP1.setFont(new java.awt.Font("HP Simplified Hans", 1, 14)); // NOI18N
        jlabel_agregarP1.setForeground(new java.awt.Color(199, 199, 199));
        jlabel_agregarP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/resources/img_iconos/duplicate_12108396.png"))); // NOI18N
        jlabel_agregarP1.setText("Agregar Productos");
        jlabel_agregarP1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_agregarP1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlabel_agregarP1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlabel_agregarP1MouseExited(evt);
            }
        });
        btn_agregar.add(jlabel_agregarP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 60));

        sidebar_panel.add(btn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 200, 60));

        btn_mostrar.setBackground(new java.awt.Color(37, 38, 38));
        btn_mostrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_mostrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlabel_mostrar.setBackground(new java.awt.Color(199, 199, 199));
        jlabel_mostrar.setFont(new java.awt.Font("HP Simplified Hans", 1, 14)); // NOI18N
        jlabel_mostrar.setForeground(new java.awt.Color(199, 199, 199));
        jlabel_mostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/resources/img_iconos/vista.png"))); // NOI18N
        jlabel_mostrar.setText("Mostrar");
        jlabel_mostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_mostrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlabel_mostrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlabel_mostrarMouseExited(evt);
            }
        });
        btn_mostrar.add(jlabel_mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 60));

        sidebar_panel.add(btn_mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 200, 60));

        btn_editar.setBackground(new java.awt.Color(37, 37, 38));
        btn_editar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_editar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlabel_editar.setBackground(new java.awt.Color(199, 199, 199));
        jlabel_editar.setFont(new java.awt.Font("HP Simplified Hans", 1, 14)); // NOI18N
        jlabel_editar.setForeground(new java.awt.Color(199, 199, 199));
        jlabel_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/resources/img_iconos/editar.png"))); // NOI18N
        jlabel_editar.setText("Editar");
        jlabel_editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_editarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlabel_editarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlabel_editarMouseExited(evt);
            }
        });
        btn_editar.add(jlabel_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 60));

        sidebar_panel.add(btn_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 200, 60));

        panel_barraAccion.setBackground(new java.awt.Color(37, 37, 50));
        panel_barraAccion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("HP Simplified Hans", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(200, 200, 200));
        jLabel3.setText("Barra de Acciones");
        panel_barraAccion.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        sidebar_panel.add(panel_barraAccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 60));

        btn_Buscar.setBackground(new java.awt.Color(37, 37, 38));
        btn_Buscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Buscar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Buscar1.setBackground(new java.awt.Color(37, 37, 38));
        btn_Buscar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Buscar1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        btn_Buscar.add(btn_Buscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 200, 60));

        jlabel_buscar1.setBackground(new java.awt.Color(199, 199, 199));
        jlabel_buscar1.setFont(new java.awt.Font("HP Simplified Hans", 1, 14)); // NOI18N
        jlabel_buscar1.setForeground(new java.awt.Color(199, 199, 199));
        jlabel_buscar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/resources/img_iconos/lupa.png"))); // NOI18N
        jlabel_buscar1.setText("Buscar ");
        jlabel_buscar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_buscar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlabel_buscar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlabel_buscar1MouseExited(evt);
            }
        });
        btn_Buscar.add(jlabel_buscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 60));

        sidebar_panel.add(btn_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 200, 60));

        btn_eliminar.setBackground(new java.awt.Color(37, 38, 39));
        btn_eliminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_eliminar.setLayout(new java.awt.BorderLayout());

        jlabel_eliminar.setFont(new java.awt.Font("HP Simplified Hans", 1, 14)); // NOI18N
        jlabel_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/resources/img_iconos/eliminar.png"))); // NOI18N
        jlabel_eliminar.setText("Eliminar");
        jlabel_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_eliminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlabel_eliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlabel_eliminarMouseExited(evt);
            }
        });
        btn_eliminar.add(jlabel_eliminar, java.awt.BorderLayout.CENTER);

        sidebar_panel.add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 200, 60));

        getContentPane().add(sidebar_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 200, 650));

        texto_bienvenida.setBackground(new java.awt.Color(51, 0, 255));
        texto_bienvenida.setFont(new java.awt.Font("HP Simplified Hans", 1, 48)); // NOI18N
        texto_bienvenida.setForeground(new java.awt.Color(199, 199, 199));
        texto_bienvenida.setText("Bienvenido al programa  ");
        texto_bienvenida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                texto_bienvenidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                texto_bienvenidaMouseExited(evt);
            }
        });
        getContentPane().add(texto_bienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 560, 70));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/resources/img_iconos/supermercado (1).png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 200, 210));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarMouseEntered
        
    }//GEN-LAST:event_btn_agregarMouseEntered
    /**
     * Event para que cambie el color cuando selecciona o pasa encima del jlabel
     * @param evt 
     */
    private void texto_bienvenidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texto_bienvenidaMouseEntered
        btn_agregar.setBackground(mouseEnterColor);
    }//GEN-LAST:event_texto_bienvenidaMouseEntered
    /**
     * 
     * @param evt 
     */
    private void texto_bienvenidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texto_bienvenidaMouseExited
        btn_agregar.setBackground(mouseExitColor);
    }//GEN-LAST:event_texto_bienvenidaMouseExited
    /**
     * Metodo para que cuando el mouse pase por encima, cambie de color
     * @param evt 
     */
    private void jlabel_mostrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_mostrarMouseEntered
        btn_mostrar.setBackground(mouseEnterColor);
    }//GEN-LAST:event_jlabel_mostrarMouseEntered
    /**
     * Metodo para que cuando el mouse salga , regrese a su color original
     * @param evt 
     */
    private void jlabel_mostrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_mostrarMouseExited
        btn_mostrar.setBackground(mouseExitColor);
    }//GEN-LAST:event_jlabel_mostrarMouseExited
    /**
     * Metodo para que cuando el mouse pase por encima, cambie de color
     * @param evt 
     */
    private void jlabel_editarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_editarMouseEntered
        btn_editar.setBackground(mouseEnterColor);
    }//GEN-LAST:event_jlabel_editarMouseEntered
    /**
     * Metodo para que cuando el mouse salga , regrese a su color original
     * @param evt 
     */
    private void jlabel_editarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_editarMouseExited
        btn_editar.setBackground(mouseExitColor);
    }//GEN-LAST:event_jlabel_editarMouseExited

    private void btn_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarMouseClicked
       
        
    }//GEN-LAST:event_btn_agregarMouseClicked
    /**
     * Metodo para que cuando el mouse pase por encima, cambie de color
     * @param evt 
     */
    private void jlabel_agregarP1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_agregarP1MouseEntered
        btn_agregar.setBackground(mouseEnterColor);
    }//GEN-LAST:event_jlabel_agregarP1MouseEntered
    /**
     * Metodo para que cuando el mouse salga , regrese a su color original
     * @param evt 
     */
    private void jlabel_agregarP1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_agregarP1MouseExited
        btn_agregar.setBackground(mouseExitColor);
    }//GEN-LAST:event_jlabel_agregarP1MouseExited
    /**
     * Metodo para que cuando pulse esa area, cambie a la ventana de agregar
     * @param evt 
     */
    private void jlabel_agregarP1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_agregarP1MouseClicked
        this.dispose();
        new AgregarView().setVisible(true);
    }//GEN-LAST:event_jlabel_agregarP1MouseClicked
    /**
     * Metodo para que cuando pulse esa area, cambie a ventana de mostrar
     * @param evt 
     */
    private void jlabel_mostrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_mostrarMouseClicked
        this.dispose();
        try {
            new MostrarView().setVisible(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jlabel_mostrarMouseClicked
    /**
     * Metodo para que cuando pulse esa area, cambie a ventana de editar
     * @param evt 
     */
    private void jlabel_editarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_editarMouseClicked
        this.dispose();
        try {
            new EditarView().setVisible(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jlabel_editarMouseClicked

    private void jlabel_buscar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_buscar1MouseClicked
        new BuscarView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jlabel_buscar1MouseClicked

    private void jlabel_buscar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_buscar1MouseEntered
        btn_Buscar.setBackground(mouseEnterColor);
    }//GEN-LAST:event_jlabel_buscar1MouseEntered

    private void jlabel_buscar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_buscar1MouseExited
        btn_Buscar.setBackground(mouseExitColor);
    }//GEN-LAST:event_jlabel_buscar1MouseExited

    private void jlabel_eliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_eliminarMouseEntered
        btn_eliminar.setBackground(mouseEnterColor);
    }//GEN-LAST:event_jlabel_eliminarMouseEntered

    private void jlabel_eliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_eliminarMouseExited
        btn_eliminar.setBackground(mouseExitColor);
    }//GEN-LAST:event_jlabel_eliminarMouseExited

    private void jlabel_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_eliminarMouseClicked
        new EliminarView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jlabel_eliminarMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_Buscar;
    private javax.swing.JPanel btn_Buscar1;
    private javax.swing.JPanel btn_agregar;
    private javax.swing.JPanel btn_editar;
    private javax.swing.JPanel btn_eliminar;
    private javax.swing.JPanel btn_mostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jlabel_agregarP1;
    private javax.swing.JLabel jlabel_buscar1;
    private javax.swing.JLabel jlabel_editar;
    private javax.swing.JLabel jlabel_eliminar;
    private javax.swing.JLabel jlabel_mostrar;
    private javax.swing.JPanel panel_barraAccion;
    private javax.swing.JPanel panel_titulo;
    private javax.swing.JPanel sidebar_panel;
    private javax.swing.JLabel texto_bienvenida;
    // End of variables declaration//GEN-END:variables
}



